CREATE TABLE TX_USER_DRIVER(
USR_ID Number(5),
USR_FIRST_NAME Varchar2(50),
USR_LAST_NAME Varchar2(100),
USR_TYPE Varchar2(20),
USR_BRAND Varchar2(100),
USR_MODEL Varchar2(100),
USR_USER_NAME Varchar2(100),
USR_PASSWORD Varchar2(100),
USR_AVAILABLE Number(1)
);

ALTER TABLE TX_USER_DRIVER ADD CONSTRAINT PK_TX_USER_DRIVER PRIMARY KEY ("USR_ID");

CREATE SEQUENCE SEQ_TX_USER_DRIVER;