CREATE TABLE TX_ROUTE(
ROU_PASSENGER_ID NUMBER(5),
ROU_DRIVER_ID NUMBER(5),
ROU_TO_LOCATION SDO_GEOMETRY,
ROU_FROM_LOCATION SDO_GEOMETRY,
ROU_START_DATE DATE,
ROU_END_DATE DATE
);

ALTER TABLE TX_ROUTE ADD CONSTRAINT PK_ROUTE PRIMARY KEY ("ROU_PASSENGER_ID", "ROU_DRIVER_ID", "ROU_START_DATE");

ALTER TABLE TX_ROUTE ADD CONSTRAINT FK_ROUTE_PSNGRID FOREIGN KEY ("ROU_PASSENGER_ID")
REFERENCES TX_USER_DRIVER("USR_ID");
ALTER TABLE TX_ROUTE ADD CONSTRAINT FK_ROUTE_DRIVERID FOREIGN KEY ("ROU_DRIVER_ID")
REFERENCES TX_USER_DRIVER("USR_ID");